import React, { useEffect, useState } from 'react';
import { AlertTriangle, Bell, CheckCheck, Info } from 'lucide-react';
import { notificationAPI } from '../lib/api';
import { Button } from './ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuTrigger } from './ui/dropdown-menu';

export default function NotificationCenter() {
  const [items, setItems] = useState([]); const load = async () => { try { setItems((await notificationAPI.getAll()).data); } catch {} };
  useEffect(() => { load(); const timer = setInterval(load, 30000); return () => clearInterval(timer); }, []);
  const unread = items.filter(item => !item.read_at).length;
  const read = async item => { if (!item.read_at) await notificationAPI.markRead(item.notification_id); load(); };
  const all = async () => { await notificationAPI.markAllRead(); load(); };
  return <DropdownMenu onOpenChange={open => open && load()}><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="relative h-11 w-11 rounded-full border border-[#17231f]/10 bg-white text-[#52665f] hover:bg-[#f7f8f4]"><Bell className="h-5 w-5" />{unread > 0 && <span className="absolute -right-0.5 -top-0.5 grid h-5 min-w-5 place-items-center rounded-full bg-[#17231f] px-1 text-[9px] font-bold text-[#d8ff61]">{unread > 9 ? '9+' : unread}</span>}</Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-[min(360px,calc(100vw-24px))] overflow-hidden rounded-2xl border-[#17231f]/10 bg-white p-0 shadow-2xl"><div className="flex items-center justify-between border-b border-[#e1e7df] p-4"><div><p className="font-extrabold text-[#17231f]">Notifications</p><p className="text-[10px] text-[#82918c]">{unread ? `${unread} unread updates` : 'You are all caught up'}</p></div>{unread > 0 && <button onClick={all} className="flex items-center gap-1 text-xs font-bold text-[#426b5f]"><CheckCheck className="h-3.5 w-3.5" />Read all</button>}</div><div className="max-h-[430px] overflow-y-auto">{items.map(item => <button key={item.notification_id} onClick={() => read(item)} className={`w-full border-b border-[#edf0eb] p-4 text-left transition hover:bg-[#f7f9f5] ${item.read_at ? '' : 'bg-[#f4fadf]'}`}><div className="flex gap-3"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg ${item.severity === 'warning' ? 'bg-amber-100 text-amber-700' : 'bg-[#e4ece7] text-[#426b5f]'}`}>{item.severity === 'warning' ? <AlertTriangle className="h-4 w-4" /> : <Info className="h-4 w-4" />}</span><span><b className="block text-sm text-[#17231f]">{item.title}</b><span className="mt-1 block text-xs leading-5 text-[#64766f]">{item.message}</span><small className="mt-2 block text-[9px] text-[#96a39f]">{new Date(item.created_at).toLocaleString()}</small></span></div></button>)}{!items.length && <div className="p-10 text-center"><Bell className="mx-auto h-7 w-7 text-[#b6c0bc]" /><p className="mt-2 text-sm text-[#7b8b86]">No notifications yet</p></div>}</div></DropdownMenuContent></DropdownMenu>;
}
