import React, { useEffect, useState } from 'react';
import { expenseAPI, tripAPI } from '../lib/api';
import { useAuth } from '../context/AuthContext';
import { Badge } from '../components/ui/badge';
import { Button } from '../components/ui/button';
import { Card, CardContent } from '../components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '../components/ui/dialog';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Check, Eye, FileUp, Loader2, Plus, Send, TrendingUp, WalletCards, X } from 'lucide-react';
import { toast } from 'sonner';

const blank = { trip_id: '', category: 'fuel', description: '', estimated_amount: '', actual_amount: '', expense_date: '', vendor: '', reference: '', receipt_file_name: '', receipt_mime_type: '', receipt_file_data: '' };
const categories = [['fuel', 'Fuel'], ['toll', 'Toll'], ['parking', 'Parking'], ['driver_allowance', 'Driver allowance'], ['transporter', 'Transporter charge'], ['loading', 'Loading'], ['unloading', 'Unloading'], ['repair', 'Trip repair'], ['fine', 'Fine'], ['other', 'Other']];
const currency = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Number(value || 0));
const errorText = error => error?.response?.data?.detail || 'Operation failed';
const badge = status => status === 'approved' ? 'bg-green-500/20 text-green-400' : status === 'rejected' ? 'bg-red-500/20 text-red-400' : status === 'submitted' ? 'bg-yellow-500/20 text-yellow-400' : 'bg-slate-700 text-slate-300';

export default function ExpensesPage() {
  const { user } = useAuth();
  const [expenses, setExpenses] = useState([]); const [profit, setProfit] = useState({ trips: [] }); const [trips, setTrips] = useState([]);
  const [loading, setLoading] = useState(true); const [tab, setTab] = useState('expenses'); const [open, setOpen] = useState(false); const [preview, setPreview] = useState(null); const [form, setForm] = useState(blank);
  const permissions = user?.permissions || []; const canCreate = permissions.includes('*') || permissions.includes('expenses.*') || permissions.includes('expenses.create'); const canApprove = permissions.includes('*') || permissions.includes('expenses.*') || permissions.includes('expenses.approve');
  const refresh = async () => { try { const [expenseResponse, profitResponse, tripResponse] = await Promise.all([expenseAPI.getAll(), expenseAPI.profitability(), tripAPI.getAll()]); setExpenses(expenseResponse.data); setProfit(profitResponse.data); setTrips(tripResponse.data); } catch (error) { toast.error(errorText(error)); } finally { setLoading(false); } };
  useEffect(() => { refresh(); }, []);
  const showCreate = () => { setForm({ ...blank, trip_id: trips.find(item => item.status !== 'cancelled')?.trip_id || '' }); setOpen(true); };
  const file = event => { const value = event.target.files?.[0]; if (!value) return; const reader = new FileReader(); reader.onload = () => setForm(current => ({ ...current, receipt_file_name: value.name, receipt_mime_type: value.type, receipt_file_data: reader.result })); reader.readAsDataURL(value); };
  const create = async event => { event.preventDefault(); try { await expenseAPI.create({ ...form, estimated_amount: Number(form.estimated_amount || 0), actual_amount: form.actual_amount === '' ? null : Number(form.actual_amount), expense_date: form.expense_date ? new Date(`${form.expense_date}T12:00:00`).toISOString() : null }); toast.success('Trip expense saved as draft'); setOpen(false); refresh(); } catch (error) { toast.error(errorText(error)); } };
  const action = async (callback, message) => { try { await callback(); toast.success(message); refresh(); } catch (error) { toast.error(errorText(error)); } };
  const viewReceipt = async id => { try { setPreview((await expenseAPI.getReceipt(id)).data); } catch (error) { toast.error(errorText(error)); } };
  if (loading) return <div className="h-64 flex items-center justify-center"><Loader2 className="animate-spin text-orange-500" /></div>;
  return <div className="space-y-6">
    <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-bold text-white">Trip Costs & Profitability</h1><p className="text-sm text-slate-400">Approve trip spending and compare operating cost against pre-tax revenue.</p></div>{canCreate && <Button onClick={showCreate} className="bg-orange-500"><Plus className="w-4 h-4 mr-2" />Add expense</Button>}</div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Stat icon={TrendingUp} label="Pre-tax revenue" value={currency(profit.revenue)} /><Stat icon={WalletCards} label="Estimated cost" value={currency(profit.estimated_cost)} /><Stat icon={WalletCards} label="Approved actual cost" value={currency(profit.approved_actual_cost)} /><Stat icon={TrendingUp} label="Realized profit" value={currency(profit.actual_profit)} /></div>
    <div className="flex gap-2 border-b border-slate-800"><Tab active={tab === 'expenses'} onClick={() => setTab('expenses')}>Expenses <Badge className="ml-1 bg-slate-700">{expenses.length}</Badge></Tab><Tab active={tab === 'profit'} onClick={() => setTab('profit')}>Profit by trip</Tab></div>
    {tab === 'expenses' ? <Table headers={['Trip / load', 'Expense', 'Estimate', 'Actual', 'Receipt', 'Status', 'Actions']} empty="No trip expenses recorded yet.">{expenses.map(item => <tr key={item.expense_id} className="border-b border-slate-800"><Cell><span className="font-mono text-white">{item.load_reference || item.trip_id}</span><br /><span className="text-xs line-clamp-1">{item.route}</span></Cell><Cell><span className="text-white capitalize">{item.category.replaceAll('_', ' ')}</span><br />{item.description}{item.vendor && <span className="text-xs block">{item.vendor}</span>}</Cell><Cell>{currency(item.estimated_amount)}</Cell><Cell className="text-white">{item.actual_amount == null ? 'Not entered' : currency(item.actual_amount)}</Cell><Cell>{item.receipt_file_name ? <Button size="icon" variant="ghost" onClick={() => viewReceipt(item.expense_id)}><Eye className="w-4 h-4" /></Button> : '—'}</Cell><Cell><Badge className={badge(item.status)}>{item.status}</Badge>{item.review_notes && <span className="text-xs text-red-400 block mt-1">{item.review_notes}</span>}</Cell><Cell><div className="flex gap-1">{item.status === 'draft' && <Button size="sm" onClick={() => action(() => expenseAPI.submit(item.expense_id), 'Expense submitted')}><Send className="w-3 h-3 mr-1" />Submit</Button>}{canApprove && item.status === 'submitted' && <><Button size="icon" onClick={() => action(() => expenseAPI.review(item.expense_id, 'approved'), 'Expense approved')} className="bg-green-600"><Check className="w-4 h-4" /></Button><Button size="icon" variant="outline" onClick={() => { const notes = window.prompt('Reason for rejection'); if (notes !== null) action(() => expenseAPI.review(item.expense_id, 'rejected', notes), 'Expense rejected'); }}><X className="w-4 h-4" /></Button></>}</div></Cell></tr>)}</Table> : <Table headers={['Load', 'Trip status', 'Revenue', 'Estimated cost', 'Approved actual', 'Pending', 'Actual profit', 'Margin']} empty="No trips available.">{profit.trips.map(item => <tr key={item.trip_id} className="border-b border-slate-800"><Cell><span className="font-mono text-white">{item.load_reference || item.trip_id}</span><br />{item.customer_name}</Cell><Cell><Badge className="bg-slate-700 text-slate-300">{item.trip_status.replaceAll('_', ' ')}</Badge></Cell><Cell>{currency(item.revenue)}</Cell><Cell>{currency(item.estimated_cost)}</Cell><Cell>{currency(item.approved_actual_cost)}</Cell><Cell>{currency(item.pending_actual_cost)}</Cell><Cell className={Number(item.actual_profit) < 0 ? 'text-red-400' : 'text-green-400'}>{currency(item.actual_profit)}</Cell><Cell>{item.actual_margin_percent == null ? '—' : `${item.actual_margin_percent}%`}</Cell></tr>)}</Table>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="bg-slate-900 border-slate-800 text-white"><DialogHeader><DialogTitle>Add trip expense</DialogTitle></DialogHeader><form onSubmit={create} className="space-y-3"><Select label="Trip" required value={form.trip_id} onChange={event => setForm({ ...form, trip_id: event.target.value })} values={trips.filter(item => item.status !== 'cancelled').map(item => [item.trip_id, `${item.customer_name} · ${item.origin} → ${item.destination}`])} /><div className="grid grid-cols-2 gap-3"><Select label="Category" value={form.category} onChange={event => setForm({ ...form, category: event.target.value })} values={categories} /><Field required label="Description" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /><Field type="number" min="0" step="0.01" label="Estimated amount" value={form.estimated_amount} onChange={event => setForm({ ...form, estimated_amount: event.target.value })} /><Field type="number" min="0" step="0.01" label="Actual amount" value={form.actual_amount} onChange={event => setForm({ ...form, actual_amount: event.target.value })} /><Field type="date" label="Expense date" value={form.expense_date} onChange={event => setForm({ ...form, expense_date: event.target.value })} /><Field label="Vendor" value={form.vendor} onChange={event => setForm({ ...form, vendor: event.target.value })} /><Field label="Reference" value={form.reference} onChange={event => setForm({ ...form, reference: event.target.value })} /></div><div><Label>Receipt (optional PDF or image, maximum 5 MB)</Label><Input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={file} className="bg-slate-800 border-slate-700 mt-1" /></div><Button className="w-full bg-orange-500">Save draft expense</Button></form></DialogContent></Dialog>
    <Dialog open={!!preview} onOpenChange={value => !value && setPreview(null)}><DialogContent className="bg-slate-900 border-slate-800 text-white max-w-4xl"><DialogHeader><DialogTitle>{preview?.file_name || 'Receipt'}</DialogTitle></DialogHeader>{preview?.mime_type === 'application/pdf' ? <iframe title="Receipt" src={preview.file_data} className="w-full h-[70vh] rounded bg-white" /> : preview && <img src={preview.file_data} alt={preview.file_name} className="max-h-[70vh] w-full object-contain rounded" />}</DialogContent></Dialog>
  </div>;
}

function Stat({ icon: Icon, label, value }) { return <Card className="bg-slate-900 border-slate-800"><CardContent className="p-4"><Icon className="w-4 h-4 text-orange-500" /><p className="text-xl text-white font-bold mt-2">{value}</p><p className="text-xs text-slate-500">{label}</p></CardContent></Card>; }
function Table({ headers, empty, children }) { return <Card className="bg-slate-900 border-slate-800"><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-slate-800 text-left text-xs uppercase text-slate-500">{headers.map(value => <th className="p-3" key={value}>{value}</th>)}</tr></thead><tbody>{children}</tbody></table>{!React.Children.count(children) && <div className="py-14 text-center text-slate-500">{empty}</div>}</CardContent></Card>; }
function Cell({ children, className = '' }) { return <td className={`p-3 text-slate-400 ${className}`}>{children}</td>; }
function Tab({ active, children, ...props }) { return <button {...props} className={`px-4 py-3 text-sm border-b-2 ${active ? 'border-orange-500 text-orange-400' : 'border-transparent text-slate-500'}`}>{children}</button>; }
function Field({ label, ...props }) { return <div><Label>{label}</Label><Input {...props} className="bg-slate-800 border-slate-700 mt-1" /></div>; }
function Select({ label, values, ...props }) { return <div><Label>{label}</Label><select {...props} className="w-full h-10 rounded border border-slate-700 bg-slate-800 px-2 mt-1"><option value="">Select</option>{values.map(([value, text]) => <option value={value} key={value}>{text}</option>)}</select></div>; }
