import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useLanguage } from '../context/LanguageContext';
import { landingCopy, landingLanguageNames } from './landingTranslations';
import { Button } from '../components/ui/button';
import ChatBox from '../components/ChatBox';
import { ArrowRight, BarChart3, BellRing, Check, ChevronRight, CircleDollarSign, Clock3, FileCheck2, Globe2, Mail, MapPin, Menu, Navigation, Phone, Route, ShieldCheck, Sparkles, Truck, Users, WalletCards, X, Zap } from 'lucide-react';

const CONTACT = { indiaPhone: '+91 91111-11185', australiaPhone: '+61 4111-85967', email: 'help.bookmyload@gmail.com', address: '211–214 Mechanic Nagar, Transport Nagar, Indore, Madhya Pradesh 452001' };

const featureIcons = [Route, Navigation, ShieldCheck, CircleDollarSign];
const reasonIcons = [Users, Clock3, WalletCards, BellRing];

export default function LandingPage() {
  const { login, user } = useAuth(); const { language, setLanguage } = useLanguage(); const navigate = useNavigate(); const [menuOpen, setMenuOpen] = useState(false); const pageLanguage = landingCopy[language] ? language : 'en'; const c = landingCopy[pageLanguage];
  const enter = () => user ? navigate(user.role === 'driver' ? '/driver' : '/dashboard') : login();
  return <div className="landing-page min-h-screen overflow-hidden bg-[#f5f4ed] text-[#12221e] selection:bg-[#d8ff61] selection:text-[#12221e]">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#071512]/80 backdrop-blur-xl">
      <div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-12">
        <a href="#top" className="flex items-center gap-3 text-white"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#d8ff61]"><Truck className="h-5 w-5 text-[#071512]" /></span><span><span className="block text-lg font-extrabold leading-none tracking-[-.04em]">BookMyLoad</span><span className="mt-1 block text-[9px] font-bold uppercase tracking-[.18em] text-white/45">{c.brandSub}</span></span></a>
        <nav className="hidden items-center gap-8 lg:flex">{c.nav.map((label,index) => <a key={label} href={['#product','#workflow','#why-us','#contact'][index]} className="text-sm font-medium text-white/65 transition hover:text-[#d8ff61]">{label}</a>)}</nav>
        <div className="hidden items-center gap-3 lg:flex"><LanguageSelect language={language} setLanguage={setLanguage} />{user ? <Link to={user.role === 'driver' ? '/driver' : '/dashboard'}><Button className="h-11 rounded-full bg-[#d8ff61] px-6 font-bold text-[#071512] hover:bg-white">{c.open}<ArrowRight className="ml-2 h-4 w-4" /></Button></Link> : <><button onClick={login} className="px-3 text-sm font-semibold text-white/75 hover:text-white">{c.signIn}</button><Button onClick={login} data-testid="login-btn" className="h-11 rounded-full bg-[#d8ff61] px-6 font-bold text-[#071512] hover:bg-white">{c.start}<ArrowRight className="ml-2 h-4 w-4" /></Button></> }</div>
        <button onClick={() => setMenuOpen(!menuOpen)} className="grid h-10 w-10 place-items-center rounded-full border border-white/15 text-white lg:hidden" aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button>
      </div>
      {menuOpen && <div className="border-t border-white/10 bg-[#071512] px-5 py-5 lg:hidden"><div className="mb-3"><LanguageSelect language={language} setLanguage={setLanguage} mobile /></div><nav className="flex flex-col gap-1">{c.nav.map((label,index) => <a key={label} href={['#product','#workflow','#why-us','#contact'][index]} onClick={() => setMenuOpen(false)} className="rounded-xl px-4 py-3 font-semibold text-white/75 hover:bg-white/5 hover:text-white">{label}</a>)}</nav><Button onClick={enter} className="mt-4 w-full rounded-full bg-[#d8ff61] text-[#071512]">{user ? c.open : c.google}</Button></div>}
    </header>

    <main id="top">
      <section className="relative min-h-[790px] bg-[#071512] pt-20 text-white lg:min-h-[860px]">
        <img src="/logistics-hero.png" alt="Freight truck travelling on a modern logistics corridor at dawn" className="absolute inset-0 h-full w-full object-cover object-[66%_center]" />
        <div className="absolute inset-0 bg-[linear-gradient(90deg,#071512_0%,rgba(7,21,18,.96)_33%,rgba(7,21,18,.56)_60%,rgba(7,21,18,.2)_100%)]" />
        <div className="absolute inset-0 bg-[linear-gradient(0deg,#071512_0%,transparent_30%)]" />
        <div className="relative mx-auto flex min-h-[710px] max-w-[1440px] items-center px-5 py-20 sm:px-8 lg:min-h-[780px] lg:px-12">
          <div className="max-w-3xl pt-10">
            <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#d8ff61]/25 bg-[#d8ff61]/10 px-4 py-2 text-xs font-bold uppercase tracking-[.14em] text-[#d8ff61]"><Sparkles className="h-3.5 w-3.5" />{c.badge}</div>
            <h1 className="max-w-3xl text-[3.25rem] font-black leading-[.94] tracking-[-.055em] sm:text-7xl lg:text-[6.4rem]">{c.hero1}<br /><span className="text-[#d8ff61]">{c.hero2}</span></h1>
            <p className="mt-7 max-w-xl text-base leading-7 text-white/66 sm:text-lg">{c.heroText}</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row">{user ? <Link to={user.role === 'driver' ? '/driver' : '/dashboard'}><Button size="lg" className="h-14 w-full rounded-full bg-[#d8ff61] px-8 text-base font-extrabold text-[#071512] hover:bg-white sm:w-auto">{c.open}<ArrowRight className="ml-2 h-5 w-5" /></Button></Link> : <Button onClick={login} size="lg" className="h-14 rounded-full bg-[#d8ff61] px-8 text-base font-extrabold text-[#071512] hover:bg-white">{c.google}<ArrowRight className="ml-2 h-5 w-5" /></Button>}<a href="#product" className="flex h-14 items-center justify-center rounded-full border border-white/20 px-7 font-bold text-white transition hover:border-white/50 hover:bg-white/5">{c.explore}</a></div>
            <div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-xs font-semibold text-white/50">{c.assurances.map(item => <span key={item} className="flex items-center gap-2"><Check className="h-4 w-4 text-[#d8ff61]" />{item}</span>)}</div>
          </div>
        </div>
        <div className="relative mx-auto -mt-24 max-w-[1440px] px-5 sm:px-8 lg:px-12"><div className="grid overflow-hidden rounded-[1.75rem] border border-white/10 bg-[#10241f]/90 shadow-2xl backdrop-blur-xl sm:grid-cols-3">{c.metrics.map(([value,label],index) => <HeroMetric key={label} icon={[Zap,FileCheck2,TrendingIcon][index]} value={value} label={label} />)}</div></div>
      </section>

      <section id="product" className="px-5 py-28 sm:px-8 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1344px]"><SectionIntro eyebrow={c.productEyebrow} title={c.productTitle} text={c.productText} /><div className="mt-14 grid gap-4 md:grid-cols-2">{c.features.map((item,index) => { const Icon = featureIcons[index]; return <article key={item[1]} className={`group relative overflow-hidden rounded-[2rem] border border-[#12221e]/10 p-7 transition duration-500 hover:-translate-y-1 hover:shadow-[0_25px_70px_rgba(18,34,30,.12)] sm:p-10 ${index === 0 ? 'bg-[#12221e] text-white' : index === 3 ? 'bg-[#d8ff61]' : 'bg-white'}`}><div className={`mb-16 flex h-12 w-12 items-center justify-center rounded-2xl ${index === 0 ? 'bg-[#d8ff61] text-[#12221e]' : 'bg-[#12221e] text-white'}`}><Icon className="h-5 w-5" /></div><p className={`text-xs font-extrabold uppercase tracking-[.16em] ${index === 0 ? 'text-[#d8ff61]' : 'text-[#497066]'}`}>{item[0]}</p><h3 className="mt-3 max-w-md text-3xl font-black tracking-[-.04em] sm:text-4xl">{item[1]}</h3><p className={`mt-4 max-w-lg leading-7 ${index === 0 ? 'text-white/55' : 'text-[#4f625d]'}`}>{item[2]}</p><ChevronRight className="absolute right-8 top-8 h-5 w-5 opacity-30 transition group-hover:translate-x-1 group-hover:opacity-100" /></article>})}</div></div></section>

      <section className="bg-[#dce6df] px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto grid max-w-[1344px] items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><span className="text-xs font-extrabold uppercase tracking-[.16em] text-[#497066]">{c.controlEyebrow}</span><h2 className="mt-5 text-4xl font-black leading-[1.02] tracking-[-.05em] sm:text-6xl">{c.controlTitle}</h2><p className="mt-6 max-w-lg leading-7 text-[#4f625d]">{c.controlText}</p><ul className="mt-8 space-y-4">{c.controlPoints.map(item => <li key={item} className="flex gap-3 font-semibold"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[#12221e] text-[#d8ff61]"><Check className="h-3.5 w-3.5" /></span>{item}</li>)}</ul></div><ProductMockup copy={c.mock} /></div></section>

      <section id="workflow" className="bg-[#071512] px-5 py-28 text-white sm:px-8 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1344px]"><SectionIntro dark eyebrow={c.workflowEyebrow} title={c.workflowTitle} text={c.workflowText} /><div className="mt-16 grid gap-px overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-4">{c.workflow.map(([title,text],index) => <article key={title} className="bg-[#0b1b17] p-7 sm:p-9"><span className="font-mono text-xs text-[#d8ff61]">{String(index + 1).padStart(2,'0')}</span><h3 className="mt-14 text-2xl font-bold tracking-[-.03em]">{title}</h3><p className="mt-4 text-sm leading-6 text-white/50">{text}</p></article>)}</div></div></section>

      <section id="why-us" className="px-5 py-28 sm:px-8 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1344px]"><div className="grid gap-12 lg:grid-cols-2"><div><SectionIntro eyebrow={c.whyEyebrow} title={c.whyTitle} text={c.whyText} /></div><div className="grid gap-4 sm:grid-cols-2">{c.reasons.map(([title,text],index) => <Reason key={title} icon={reasonIcons[index]} title={title} text={text} />)}</div></div></div></section>

      <section className="px-5 pb-28 sm:px-8 lg:px-12 lg:pb-36"><div className="relative mx-auto max-w-[1344px] overflow-hidden rounded-[2.5rem] bg-[#d8ff61] px-6 py-16 sm:px-12 lg:px-20 lg:py-20"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full border-[55px] border-[#12221e]/5" /><div className="relative max-w-3xl"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#497066]">{c.ctaEyebrow}</p><h2 className="mt-5 text-4xl font-black leading-[.98] tracking-[-.05em] sm:text-6xl">{c.ctaTitle}</h2><p className="mt-5 max-w-xl text-[#3f554f]">{c.ctaText}</p><Button onClick={enter} className="mt-8 h-14 rounded-full bg-[#12221e] px-8 font-extrabold text-white hover:bg-[#24433b]">{user ? c.open : c.google}<ArrowRight className="ml-2 h-5 w-5" /></Button></div></div></section>
    </main>

    <footer id="contact" className="bg-[#071512] px-5 pb-8 pt-20 text-white sm:px-8 lg:px-12"><div className="mx-auto max-w-[1344px]"><div className="grid gap-12 border-b border-white/10 pb-16 md:grid-cols-2 lg:grid-cols-4"><div className="lg:col-span-2"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#d8ff61]"><Truck className="h-5 w-5 text-[#071512]" /></span><span className="text-xl font-extrabold tracking-[-.04em]">BookMyLoad</span></div><p className="mt-5 max-w-sm leading-7 text-white/45">{c.footerText}</p></div><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d8ff61]">{c.contact}</p><div className="mt-5 space-y-3 text-sm text-white/60"><a className="flex items-center gap-2 hover:text-white" href={`tel:${CONTACT.indiaPhone}`}><Phone className="h-4 w-4" />India · {CONTACT.indiaPhone}</a><a className="flex items-center gap-2 hover:text-white" href={`tel:${CONTACT.australiaPhone}`}><Globe2 className="h-4 w-4" />Australia · {CONTACT.australiaPhone}</a><a className="flex items-center gap-2 hover:text-white" href={`mailto:${CONTACT.email}`}><Mail className="h-4 w-4" />{CONTACT.email}</a></div></div><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d8ff61]">{c.office}</p><p className="mt-5 flex gap-2 text-sm leading-6 text-white/60"><MapPin className="mt-1 h-4 w-4 shrink-0" />{CONTACT.address}</p></div></div><div className="flex flex-col gap-3 py-7 text-xs text-white/35 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} BookMyLoad. {c.rights}</p><p>{c.designed}</p></div></div></footer>
    <ChatBox />
  </div>;
}

function HeroMetric({ icon: Icon, value, label }) { return <div className="flex items-center gap-4 border-b border-white/10 px-6 py-6 last:border-0 sm:border-b-0 sm:border-r sm:last:border-r-0 lg:px-9"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#d8ff61]/10 text-[#d8ff61]"><Icon className="h-5 w-5" /></span><span><strong className="block text-lg font-extrabold text-white">{value}</strong><span className="text-xs text-white/45">{label}</span></span></div>; }
function TrendingIcon(props) { return <BarChart3 {...props} />; }
function SectionIntro({ eyebrow, title, text, dark = false }) { return <div className="max-w-3xl"><p className={`text-xs font-extrabold uppercase tracking-[.2em] ${dark ? 'text-[#d8ff61]' : 'text-[#497066]'}`}>{eyebrow}</p><h2 className={`mt-5 text-4xl font-black leading-[1.02] tracking-[-.055em] sm:text-6xl ${dark ? 'text-white' : ''}`}>{title}</h2><p className={`mt-5 max-w-2xl text-base leading-7 ${dark ? 'text-white/50' : 'text-[#4f625d]'}`}>{text}</p></div>; }
function Reason({ icon: Icon, title, text }) { return <article className="rounded-[1.5rem] border border-[#12221e]/10 bg-white p-6"><Icon className="h-5 w-5 text-[#497066]" /><h3 className="mt-8 text-xl font-extrabold tracking-[-.035em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#60706c]">{text}</p></article>; }
function ProductMockup({ copy }) { return <div className="rounded-[2rem] bg-[#071512] p-3 shadow-[0_35px_100px_rgba(18,34,30,.3)] sm:p-5"><div className="overflow-hidden rounded-[1.25rem] border border-white/10 bg-[#0c1c18]"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div className="flex gap-1.5"><i className="h-2 w-2 rounded-full bg-white/20" /><i className="h-2 w-2 rounded-full bg-white/20" /><i className="h-2 w-2 rounded-full bg-[#d8ff61]" /></div><span className="text-[10px] font-bold uppercase tracking-[.15em] text-white/30">{copy.overview}</span></div><div className="grid gap-3 p-4 sm:grid-cols-3"><MockStat label={copy.active} value="12" accent /><MockStat label={copy.onTime} value="94%" /><MockStat label={copy.margin} value="28.4%" /></div><div className="grid gap-3 px-4 pb-4 sm:grid-cols-[1.25fr_.75fr]"><div className="rounded-xl bg-white/[.04] p-4"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-white/60">{copy.movements}</span><span className="h-2 w-2 rounded-full bg-[#d8ff61] shadow-[0_0_15px_#d8ff61]" /></div><div className="relative mt-5 h-40 overflow-hidden rounded-lg bg-[#132823]"><div className="absolute inset-0 opacity-20" style={{backgroundImage:'linear-gradient(rgba(255,255,255,.12) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.12) 1px,transparent 1px)',backgroundSize:'28px 28px'}} /><div className="absolute left-[14%] top-[62%] h-1 w-[68%] -rotate-12 rounded-full bg-[#d8ff61]/50" /><MapPin className="absolute right-[17%] top-[30%] h-6 w-6 text-[#d8ff61]" /><Truck className="absolute left-[35%] top-[54%] h-6 w-6 text-white" /></div></div><div className="space-y-2 rounded-xl bg-white/[.04] p-4"><span className="text-xs font-semibold text-white/60">{copy.attention}</span>{copy.alerts.map((label,index) => <div key={label} className="flex items-center justify-between rounded-lg bg-white/[.04] px-3 py-3 text-xs text-white/55"><span>{label}</span><b className="text-[#d8ff61]">{[2,4,3][index]}</b></div>)}</div></div></div></div>; }
function MockStat({ label, value, accent }) { return <div className={`rounded-xl p-4 ${accent ? 'bg-[#d8ff61] text-[#071512]' : 'bg-white/[.04] text-white'}`}><span className={`text-[10px] uppercase tracking-[.16em] ${accent ? 'text-[#30443e]' : 'text-white/35'}`}>{label}</span><strong className="mt-3 block text-2xl">{value}</strong></div>; }
function LanguageSelect({ language, setLanguage, mobile = false }) { return <label className={`flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 text-white/75 ${mobile ? 'h-11 w-full' : 'h-10'}`}><Globe2 className="h-4 w-4 text-[#d8ff61]" /><select aria-label="Language" value={landingLanguageNames[language] ? language : 'en'} onChange={event => setLanguage(event.target.value)} className="min-w-0 flex-1 cursor-pointer bg-transparent text-sm font-semibold outline-none">{Object.entries(landingLanguageNames).map(([code,name]) => <option key={code} value={code} className="bg-[#071512] text-white">{name}</option>)}</select></label>; }
