import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { customerAPI, driverAPI, reportsAPI, vehicleAPI } from '../lib/api';
import { Badge } from '../components/ui/badge';
import { Button } from '../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { BarChart3, Banknote, Download, FileText, Loader2, Printer, RefreshCw, Route, TrendingUp, WalletCards } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell as ChartCell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { toast } from 'sonner';

const COLORS = ['#f97316', '#3b82f6', '#22c55e', '#eab308', '#ef4444', '#8b5cf6', '#06b6d4'];
const formatDate = value => value.toISOString().slice(0, 10);
const initialFilters = { start_date: formatDate(new Date(Date.now() - 29 * 86400000)), end_date: formatDate(new Date()), customer_id: '', driver_id: '', vehicle_id: '', load_status: '', invoice_status: '', expense_category: '' };
const currency = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(value || 0));
const errorText = error => error?.response?.data?.detail || 'Failed to load report';
const query = filters => Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== '').map(([key, value]) => [key, key.endsWith('_date') ? new Date(`${value}${key === 'end_date' ? 'T23:59:59' : 'T00:00:00'}`).toISOString() : value]));

export default function ReportsPage() {
  const [filters, setFilters] = useState(initialFilters); const [applied, setApplied] = useState(initialFilters); const [report, setReport] = useState(null); const [options, setOptions] = useState({ customers: [], drivers: [], vehicles: [] });
  const [loading, setLoading] = useState(true); const [tab, setTab] = useState('trips'); const [exporting, setExporting] = useState(false);
  const load = async selected => { setLoading(true); try { const response = await reportsAPI.overview(query(selected)); setReport(response.data); setApplied(selected); } catch (error) { toast.error(errorText(error)); } finally { setLoading(false); } };
  useEffect(() => { Promise.all([customerAPI.getAll(), driverAPI.getAll(), vehicleAPI.getAll()]).then(([customers, drivers, vehicles]) => setOptions({ customers: customers.data, drivers: drivers.data, vehicles: vehicles.data })).catch(() => toast.error('Failed to load report filters')); load(initialFilters); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const apply = event => { event.preventDefault(); load(filters); };
  const exportCsv = async () => { setExporting(true); try { const response = await reportsAPI.exportCsv(tab === 'ageing' ? 'trips' : tab, query(applied)); const url = URL.createObjectURL(response.data); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `bookmyload-${tab}-${applied.start_date}-to-${applied.end_date}.csv`; anchor.click(); URL.revokeObjectURL(url); toast.success('CSV exported'); } catch (error) { toast.error(errorText(error)); } finally { setExporting(false); } };
  const statusData = useMemo(() => Object.entries(report?.trip_statuses || {}).map(([name, value]) => ({ name: name.replaceAll('_', ' '), value })), [report]);
  if (!report && loading) return <div className="h-64 flex items-center justify-center"><Loader2 className="animate-spin text-orange-500" /></div>;
  const summary = report?.summary || {};
  return <div data-testid="reports-page" className="space-y-6 print:bg-white print:text-black">
    <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-bold text-white print:text-black">Reports & Analytics</h1><p className="text-sm text-slate-400 print:text-slate-600">Real operational and financial performance · {applied.start_date} to {applied.end_date}</p></div><div className="flex gap-2 print:hidden"><Button variant="outline" onClick={() => window.print()}><Printer className="w-4 h-4 mr-2" />Print / PDF</Button><Button onClick={exportCsv} disabled={exporting || tab === 'ageing'} className="bg-orange-500">{exporting ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Download className="w-4 h-4 mr-2" />}Export CSV</Button></div></div>
    <Card className="bg-slate-900 border-slate-800 print:hidden"><CardContent className="p-4"><form onSubmit={apply} className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Field type="date" label="From" value={filters.start_date} onChange={event => setFilters({ ...filters, start_date: event.target.value })} /><Field type="date" label="To" value={filters.end_date} onChange={event => setFilters({ ...filters, end_date: event.target.value })} /><Select label="Customer" value={filters.customer_id} onChange={event => setFilters({ ...filters, customer_id: event.target.value })} values={options.customers.map(item => [item.customer_id, item.name])} /><Select label="Driver" value={filters.driver_id} onChange={event => setFilters({ ...filters, driver_id: event.target.value })} values={options.drivers.map(item => [item.driver_id, item.name])} /><Select label="Vehicle" value={filters.vehicle_id} onChange={event => setFilters({ ...filters, vehicle_id: event.target.value })} values={options.vehicles.map(item => [item.vehicle_id, item.registration_number])} /><Select label="Load status" value={filters.load_status} onChange={event => setFilters({ ...filters, load_status: event.target.value })} values={['draft','submitted','approved','scheduled','allocated','in_execution','delivered','closed','rejected','cancelled'].map(item => [item, item.replaceAll('_',' ')])} /><Select label="Invoice status" value={filters.invoice_status} onChange={event => setFilters({ ...filters, invoice_status: event.target.value })} values={['draft','issued','partially_paid','paid','overdue'].map(item => [item, item.replaceAll('_',' ')])} /><Select label="Expense category" value={filters.expense_category} onChange={event => setFilters({ ...filters, expense_category: event.target.value })} values={['fuel','toll','parking','driver_allowance','transporter','loading','unloading','repair','fine','other'].map(item => [item, item.replaceAll('_',' ')])} /><div className="lg:col-span-4 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => { setFilters(initialFilters); load(initialFilters); }}>Reset</Button><Button type="submit" disabled={loading} className="bg-orange-500">{loading ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <RefreshCw className="w-4 h-4 mr-2" />}Apply filters</Button></div></form></CardContent></Card>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Stat icon={FileText} label="Loads / completed trips" value={`${summary.loads || 0} / ${summary.completed_trips || 0}`} note={`${summary.completion_rate || 0}% trip completion`} /><Stat icon={Banknote} label="Pre-tax revenue" value={currency(summary.revenue)} note={`${currency(summary.collected)} collected incl. tax`} /><Stat icon={WalletCards} label="Approved trip costs" value={currency(summary.approved_expenses)} note={`${summary.pending_expense_approvals || 0} awaiting approval`} /><Stat icon={TrendingUp} label="Profit / margin" value={currency(summary.profit)} note={summary.margin_percent == null ? 'No revenue' : `${summary.margin_percent}% margin`} /></div>
    <div className="grid lg:grid-cols-2 gap-4"><ChartCard title="Revenue, cost and profit trend" icon={TrendingUp}><ResponsiveContainer width="100%" height={280}><AreaChart data={report?.trend || []}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="period" stroke="#94a3b8" fontSize={11} /><YAxis stroke="#94a3b8" fontSize={11} tickFormatter={value => `₹${Math.round(value / 1000)}k`} /><Tooltip contentStyle={tooltipStyle} formatter={value => currency(value)} /><Legend /><Area type="monotone" dataKey="revenue" stroke="#f97316" fill="#f9731633" /><Area type="monotone" dataKey="cost" stroke="#ef4444" fill="#ef444422" /><Area type="monotone" dataKey="profit" stroke="#22c55e" fill="#22c55e22" /></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Trip status distribution" icon={Route}>{statusData.length ? <ResponsiveContainer width="100%" height={280}><PieChart><Pie data={statusData} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={90} label>{statusData.map((item, index) => <Cell key={item.name} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip contentStyle={tooltipStyle} /></PieChart></ResponsiveContainer> : <Empty />}</ChartCard></div>
    <div className="grid lg:grid-cols-2 gap-4"><ChartCard title="Expense category breakdown" icon={WalletCards}>{report?.expense_categories?.length ? <ResponsiveContainer width="100%" height={260}><BarChart data={report.expense_categories}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="category" stroke="#94a3b8" fontSize={11} /><YAxis stroke="#94a3b8" fontSize={11} /><Tooltip contentStyle={tooltipStyle} formatter={value => currency(value)} /><Bar dataKey="amount" fill="#f97316" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer> : <Empty />}</ChartCard><ChartCard title="Invoice ageing" icon={BarChart3}><ResponsiveContainer width="100%" height={260}><BarChart data={Object.entries(report?.invoice_ageing || {}).map(([bucket, amount]) => ({ bucket: bucket.replaceAll('_',' '), amount }))}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="bucket" stroke="#94a3b8" fontSize={11} /><YAxis stroke="#94a3b8" fontSize={11} /><Tooltip contentStyle={tooltipStyle} formatter={value => currency(value)} /><Bar dataKey="amount" fill="#3b82f6" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></ChartCard></div>
    <div className="flex gap-1 overflow-x-auto border-b border-slate-800 print:hidden">{[['trips','Trips'],['customers','Customers'],['drivers','Drivers'],['vehicles','Vehicles'],['ageing','Collection ageing']].map(([key,label]) => <button key={key} onClick={() => setTab(key)} className={`px-4 py-3 whitespace-nowrap text-sm border-b-2 ${tab === key ? 'border-orange-500 text-orange-400' : 'border-transparent text-slate-500'}`}>{label}</button>)}</div>
    {tab === 'trips' && <DataTable headers={['Load','Customer','Driver / vehicle','Date','Status','Revenue','Cost','Profit']} rows={report.trips} render={item => <tr key={item.trip_id} className="border-b border-slate-800"><Cell><Link to="/dashboard/trips" className="font-mono text-orange-400">{item.load_reference || item.trip_id}</Link></Cell><Cell>{item.customer_name}</Cell><Cell>{item.driver_name || '—'}<br /><span className="text-xs">{item.vehicle || '—'}</span></Cell><Cell>{new Date(item.scheduled_date).toLocaleDateString()}</Cell><Cell><Status value={item.status} /></Cell><Cell>{currency(item.revenue)}</Cell><Cell>{currency(item.cost)}</Cell><Cell className={Number(item.profit) < 0 ? 'text-red-400' : 'text-green-400'}>{currency(item.profit)}</Cell></tr>} />}
    {tab === 'customers' && <DataTable headers={['Customer','Loads','Completed trips','Revenue','Cost','Profit','Outstanding']} rows={report.customers} render={item => <tr key={item.customer_id} className="border-b border-slate-800"><Cell className="text-white">{item.customer_name}</Cell><Cell>{item.loads}</Cell><Cell>{item.completed_trips}</Cell><Cell>{currency(item.revenue)}</Cell><Cell>{currency(item.cost)}</Cell><Cell className="text-green-400">{currency(item.profit)}</Cell><Cell>{currency(item.outstanding)}</Cell></tr>} />}
    {tab === 'drivers' && <DataTable headers={['Driver','Trips','Completed','Completion rate','Distance']} rows={report.drivers} render={item => <tr key={item.driver_id} className="border-b border-slate-800"><Cell className="text-white">{item.driver_name}</Cell><Cell>{item.trips}</Cell><Cell>{item.completed}</Cell><Cell>{item.completion_rate}%</Cell><Cell>{item.distance_km} km</Cell></tr>} />}
    {tab === 'vehicles' && <DataTable headers={['Vehicle','Trips','Completed','Distance']} rows={report.vehicles} render={item => <tr key={item.vehicle_id} className="border-b border-slate-800"><Cell className="font-mono text-white">{item.registration_number}</Cell><Cell>{item.trips}</Cell><Cell>{item.completed}</Cell><Cell>{item.distance_km} km</Cell></tr>} />}
    {tab === 'ageing' && <DataTable headers={['Age bucket','Outstanding amount']} rows={Object.entries(report.invoice_ageing).map(([bucket, amount]) => ({ bucket, amount }))} render={item => <tr key={item.bucket} className="border-b border-slate-800"><Cell className="capitalize text-white">{item.bucket.replaceAll('_',' ')}</Cell><Cell>{currency(item.amount)}</Cell></tr>} />}
    <p className="text-xs text-slate-500">Profit excludes GST and uses only approved actual trip expenses. Pending or rejected expenses do not reduce realized profit.</p>
  </div>;
}

const tooltipStyle = { backgroundColor: '#0f172a', border: '1px solid #334155', borderRadius: 8 };
function Stat({ icon: Icon, label, value, note }) { return <Card className="bg-slate-900 border-slate-800"><CardContent className="p-4"><Icon className="w-5 h-5 text-orange-500" /><p className="text-xs text-slate-500 mt-3">{label}</p><p className="text-xl font-bold text-white mt-1">{value}</p><p className="text-xs text-slate-500 mt-1">{note}</p></CardContent></Card>; }
function ChartCard({ title, icon: Icon, children }) { return <Card className="bg-slate-900 border-slate-800"><CardHeader><CardTitle className="text-base text-white flex gap-2"><Icon className="w-5 h-5 text-orange-500" />{title}</CardTitle></CardHeader><CardContent>{children}</CardContent></Card>; }
function Empty() { return <div className="h-[260px] flex items-center justify-center text-slate-500">No data for selected filters.</div>; }
function DataTable({ headers, rows, render }) { return <Card className="bg-slate-900 border-slate-800"><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-slate-800 text-left text-xs uppercase text-slate-500">{headers.map(item => <th key={item} className="p-3">{item}</th>)}</tr></thead><tbody>{rows.map(render)}</tbody></table>{!rows.length && <div className="py-12 text-center text-slate-500">No records match the filters.</div>}</CardContent></Card>; }
function Cell({ children, className = '', ...props }) { return props.fill ? <ChartCell {...props} /> : <td className={`p-3 text-slate-400 ${className}`}>{children}</td>; }
function Status({ value }) { return <Badge className="bg-slate-700 text-slate-300 capitalize">{value.replaceAll('_',' ')}</Badge>; }
function Field({ label, ...props }) { return <div><Label>{label}</Label><Input {...props} className="mt-1 bg-slate-800 border-slate-700" /></div>; }
function Select({ label, values, ...props }) { return <div><Label>{label}</Label><select {...props} className="mt-1 h-10 w-full rounded border border-slate-700 bg-slate-800 px-2 capitalize"><option value="">All</option>{values.map(([value,labelValue]) => <option key={value} value={value}>{labelValue}</option>)}</select></div>; }
